---
title: "EPID639 Epidemiologic Data Analysis in R"
subtitle: "Install Packages for Base Project"
format: html
editor: source
---


## General code for all sessions

```{r}
#| label: install
#| echo: true

options(repos="https://cran.rstudio.com")


# General markdown, tidyverse

#install.packages("markdown")

#install.packages("rmarkdown")

#install.packages("knitr")

install.packages("tidyverse")

#install.packages("shiny")

```
## Check install success

```{r}
#| label: check-install-success

#library(rmarkdown)
#library(knitr)
library(tidyverse)

```

## Specific code for class sections


```{r}
#| label: install-packages-specific
#| echo: true

# Unfiled

install.packages("haven")

install.packages("epiDisplay")

install.packages("gmodels")

install.packages("foreign")

install.packages("Hmisc")

install.packages("car")

install.packages("corrplot")

install.packages("GGally")

install.packages("vioplot") # I don't think I need this anymore

install.packages("forestplot") # I don't think I need this anymore

install.packages("gt")

install.packages("expss")

# simcasual package for drawing a DAG and simulating data
install.packages("simcausal")

install.packages("easystats") # Not currently incorporated in class, recommended by 2023 GSIs
```


```{r}
#| label: install-packages-specific
#| echo: true

# Packages session 1

install.packages("styler")

install.packages("janitor")

# Datasets session 2

install.packages("here")

install.packages("nhanesA")

install.packages("sjlabelled")

install.packages("xlsx")

install.packages("writexl")

#install.packages("visR") #consort diagrams

install.packages("devtools") # visR recently kicked off of CRAN, download from github

devtools::install_github("openpharma/visR") 

# Graphing session 3

install.packages("ggplot2") # This comes with the tidyverse 

install.packages("ggpubr") 

# Error with ggpubr in 2023, installing dependencies one by one
# install.packages("RcppEigen") # I think this comes with the tidyverse 
# install.packages("lme4") # I think this comes with the tidyverse 
# install.packages("pbkrtest") # I think this comes with the tidyverse 
# install.packages("car") # I think this comes with the tidyverse 
# install.packages("rstatix") # I think this comes with the tidyverse 
# install.packages("ggpubr") # I think this comes with the tidyverse 

install.packages("vidiris")

install.packages("RColorBrewer")

install.packages("remotes")
remotes::install_github("MatthewBJane/theme_park")

# Can use patchwork package to stitch plots together instead of ggarrange() !!!
install.packages("patchwork")

# Descriptive statistics session 4

install.packages("gtsummary")

install.packages("flextable")

# Hypothesis testing session 5

install.packages("infer")

install.packages("ggcorrplot")

# Regression packages? session 6

install.packages("ggpubr")

install.packages("broom")

# Advanced session 7

install.packages("survey")

install.packages("rmeta")

```




